[package]
name = "rsdctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
parse_wiki_text = "0"
reqwest = { version = "0", features = ["blocking"] }
serde_json = "1"
eframe = "0"
egui-notify = "0"
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
keyboard-types = "0"